address: "localhost:40002"
database:
  driver: postgres
  host: localhost
  port: 5432
  user: postgres
  dbname: logistics_management_system
kafka_config:
  brokers:
    - "localhost:9092"
  topic: "order-events"