address: "localhost:40003"
database:
  driver: postgres
  host: localhost
  port: 5432
  user: postgres
  dbname: logistics_management_system
redis_config:
  address: "127.0.0.1:6379"
  password: ""
  db: 0
  pool_size: 100
  min_idle_conns: 10
  max_retries: 3
  dial_timeout_seconds: 30
  read_timeout_seconds: 10
  write_timeout_seconds: 10
kafka_config:
  brokers:
    - "localhost:9092"
  topic: "order-events"



