// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: warehouse_service/warehouse_service.proto

package warehouse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockRequest) Reset() {
	*x = CheckStockRequest{}
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockRequest) ProtoMessage() {}

func (x *CheckStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockRequest.ProtoReflect.Descriptor instead.
func (*CheckStockRequest) Descriptor() ([]byte, []int) {
	return file_warehouse_service_warehouse_service_proto_rawDescGZIP(), []int{0}
}

func (x *CheckStockRequest) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckStockResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Available     bool                      `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Items         []*StockItemWithWarehouse `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Message       string                    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockResponse) Reset() {
	*x = CheckStockResponse{}
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockResponse) ProtoMessage() {}

func (x *CheckStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockResponse.ProtoReflect.Descriptor instead.
func (*CheckStockResponse) Descriptor() ([]byte, []int) {
	return file_warehouse_service_warehouse_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckStockResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckStockResponse) GetItems() []*StockItemWithWarehouse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CheckStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetWarehouseStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stocks        []*Stock               `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehouseStockResponse) Reset() {
	*x = GetWarehouseStockResponse{}
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehouseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehouseStockResponse) ProtoMessage() {}

func (x *GetWarehouseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehouseStockResponse.ProtoReflect.Descriptor instead.
func (*GetWarehouseStockResponse) Descriptor() ([]byte, []int) {
	return file_warehouse_service_warehouse_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetWarehouseStockResponse) GetStocks() []*Stock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type UpdateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Time          int64                  `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_warehouse_service_warehouse_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStockRequest) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UpdateStockRequest) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type UpdateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockResponse) Reset() {
	*x = UpdateStockResponse{}
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockResponse) ProtoMessage() {}

func (x *UpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_warehouse_service_warehouse_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Time          int64                  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_warehouse_service_warehouse_service_proto_rawDescGZIP(), []int{5}
}

func (x *StockItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *StockItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *StockItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockItem) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type StockItemWithWarehouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductName   string                 `protobuf:"bytes,1,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItemWithWarehouse) Reset() {
	*x = StockItemWithWarehouse{}
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItemWithWarehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItemWithWarehouse) ProtoMessage() {}

func (x *StockItemWithWarehouse) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItemWithWarehouse.ProtoReflect.Descriptor instead.
func (*StockItemWithWarehouse) Descriptor() ([]byte, []int) {
	return file_warehouse_service_warehouse_service_proto_rawDescGZIP(), []int{6}
}

func (x *StockItemWithWarehouse) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *StockItemWithWarehouse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Stock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Time          int64                  `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_service_warehouse_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_warehouse_service_warehouse_service_proto_rawDescGZIP(), []int{7}
}

func (x *Stock) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Stock) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Stock) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Stock) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Stock) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_warehouse_service_warehouse_service_proto protoreflect.FileDescriptor

const file_warehouse_service_warehouse_service_proto_rawDesc = "" +
	"\n" +
	")warehouse_service/warehouse_service.proto\x12\twarehouse\x1a\x1bgoogle/protobuf/empty.proto\"?\n" +
	"\x11CheckStockRequest\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.warehouse.StockItemR\x05items\"\x85\x01\n" +
	"\x12CheckStockResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.warehouse.StockItemWithWarehouseR\x05items\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"E\n" +
	"\x19GetWarehouseStockResponse\x12(\n" +
	"\x06stocks\x18\x01 \x03(\v2\x10.warehouse.StockR\x06stocks\"T\n" +
	"\x12UpdateStockRequest\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.warehouse.StockItemR\x05items\x12\x12\n" +
	"\x04Time\x18\x02 \x01(\x03R\x04Time\"/\n" +
	"\x13UpdateStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"}\n" +
	"\tStockItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x03R\x04time\"W\n" +
	"\x16StockItemWithWarehouse\x12!\n" +
	"\fproduct_name\x18\x01 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\x8f\x01\n" +
	"\x05Stock\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x03R\x04time2\x8a\x02\n" +
	"\x10WarehouseService\x12U\n" +
	"\x16CheckStockAvailability\x12\x1c.warehouse.CheckStockRequest\x1a\x1d.warehouse.CheckStockResponse\x12Q\n" +
	"\x11GetWarehouseStock\x12\x16.google.protobuf.Empty\x1a$.warehouse.GetWarehouseStockResponse\x12L\n" +
	"\vUpdateStock\x12\x1d.warehouse.UpdateStockRequest\x1a\x1e.warehouse.UpdateStockResponseB\fZ\n" +
	"/warehouseb\x06proto3"

var (
	file_warehouse_service_warehouse_service_proto_rawDescOnce sync.Once
	file_warehouse_service_warehouse_service_proto_rawDescData []byte
)

func file_warehouse_service_warehouse_service_proto_rawDescGZIP() []byte {
	file_warehouse_service_warehouse_service_proto_rawDescOnce.Do(func() {
		file_warehouse_service_warehouse_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warehouse_service_warehouse_service_proto_rawDesc), len(file_warehouse_service_warehouse_service_proto_rawDesc)))
	})
	return file_warehouse_service_warehouse_service_proto_rawDescData
}

var file_warehouse_service_warehouse_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_warehouse_service_warehouse_service_proto_goTypes = []any{
	(*CheckStockRequest)(nil),         // 0: warehouse.CheckStockRequest
	(*CheckStockResponse)(nil),        // 1: warehouse.CheckStockResponse
	(*GetWarehouseStockResponse)(nil), // 2: warehouse.GetWarehouseStockResponse
	(*UpdateStockRequest)(nil),        // 3: warehouse.UpdateStockRequest
	(*UpdateStockResponse)(nil),       // 4: warehouse.UpdateStockResponse
	(*StockItem)(nil),                 // 5: warehouse.StockItem
	(*StockItemWithWarehouse)(nil),    // 6: warehouse.StockItemWithWarehouse
	(*Stock)(nil),                     // 7: warehouse.Stock
	(*emptypb.Empty)(nil),             // 8: google.protobuf.Empty
}
var file_warehouse_service_warehouse_service_proto_depIdxs = []int32{
	5, // 0: warehouse.CheckStockRequest.items:type_name -> warehouse.StockItem
	6, // 1: warehouse.CheckStockResponse.items:type_name -> warehouse.StockItemWithWarehouse
	7, // 2: warehouse.GetWarehouseStockResponse.stocks:type_name -> warehouse.Stock
	5, // 3: warehouse.UpdateStockRequest.items:type_name -> warehouse.StockItem
	0, // 4: warehouse.WarehouseService.CheckStockAvailability:input_type -> warehouse.CheckStockRequest
	8, // 5: warehouse.WarehouseService.GetWarehouseStock:input_type -> google.protobuf.Empty
	3, // 6: warehouse.WarehouseService.UpdateStock:input_type -> warehouse.UpdateStockRequest
	1, // 7: warehouse.WarehouseService.CheckStockAvailability:output_type -> warehouse.CheckStockResponse
	2, // 8: warehouse.WarehouseService.GetWarehouseStock:output_type -> warehouse.GetWarehouseStockResponse
	4, // 9: warehouse.WarehouseService.UpdateStock:output_type -> warehouse.UpdateStockResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_warehouse_service_warehouse_service_proto_init() }
func file_warehouse_service_warehouse_service_proto_init() {
	if File_warehouse_service_warehouse_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warehouse_service_warehouse_service_proto_rawDesc), len(file_warehouse_service_warehouse_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warehouse_service_warehouse_service_proto_goTypes,
		DependencyIndexes: file_warehouse_service_warehouse_service_proto_depIdxs,
		MessageInfos:      file_warehouse_service_warehouse_service_proto_msgTypes,
	}.Build()
	File_warehouse_service_warehouse_service_proto = out.File
	file_warehouse_service_warehouse_service_proto_goTypes = nil
	file_warehouse_service_warehouse_service_proto_depIdxs = nil
}
